[package]
name = "wasmtime-crate-zig"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.81"
wasmtime = "18.0.3"
wasi-common = "18.0.3"
wasmtime-wasi = "18.0.3"
